In [1]:
import pandas as pd

URI_TREINO = "https://github.com/tgcsantos/quaretenadados/blob/master/DADOS_TREINO.csv?raw=true"
URI_TESTE = "https://github.com/tgcsantos/quaretenadados/raw/master/DADOS_TESTE.csv"
URI_DESAFIOQT = "https://github.com/tgcsantos/quaretenadados/raw/master/DESAFIOQT.csv"

dados_treino = pd.read_csv(URI_TREINO)
dados_teste = pd.read_csv(URI_TESTE)
dados_desafioqt = pd.read_csv(URI_DESAFIOQT)

erro_treino = "Erro ao carregar dados de treino"
erro_teste = "Erro ao carregar dados de teste"
erro_desafioqt = "Erro ao carregar dados de submissão"

assert dados_treino.shape == (150000, 5), erro_treino
assert dados_teste.shape == (20000, 5), erro_teste
assert dados_desafioqt.shape == (10000, 5), erro_desafioqt

In [2]:
coluna_label = 'NU_NOTA_LC'
coluna_features = ['NU_NOTA_CN', 'NU_NOTA_CH', 'NU_NOTA_MT', 'NU_NOTA_REDACAO']

X_treino = dados_treino[coluna_features] #.to_numpy()
Y_treino = dados_treino[coluna_label] #.to_numpy()
X_teste = dados_teste[coluna_features] #.to_numpy()
Y_teste = dados_teste[coluna_label] #.to_numpy()

In [3]:
#Exemplo de classificação com Dummy
from sklearn.dummy import DummyRegressor
from sklearn.metrics import mean_squared_error

modelo_dummy = DummyRegressor()
modelo_dummy.fit(X_treino, Y_treino)
dummy_predicoes = modelo_dummy.predict(X_teste)

avaliacao_dummy = mean_squared_error(Y_teste, dummy_predicoes)

print(f"Minha avaliação nos dados de teste foi de {avaliacao_dummy}")

Minha avaliação nos dados de teste foi de 5219.286870186777


In [4]:
from sklearn.svm import LinearSVR
from sklearn.metrics import mean_squared_error

modelo = LinearSVR(max_iter = 100000)
modelo.fit(X_treino, Y_treino)

C:\Users\gabgm\anaconda3\lib\site-packages\sklearn\svm\_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


LinearSVR(C=1.0, dual=True, epsilon=0.0, fit_intercept=True,
          intercept_scaling=1.0, loss='epsilon_insensitive', max_iter=100000,
          random_state=None, tol=0.0001, verbose=0)

In [5]:
previsao_LSVR = modelo.predict(X_teste)
previsao_LSVR

array([545.6325361 , 460.35184663, 662.36827901, ..., 536.12184664,
       563.0509158 , 491.37498149])

In [7]:
mean_squared_error(Y_teste, previsao_LSVR)

2274.392203693615

In [ ]:
#from sklearn.tree import DecisionTreeRegressor

#modelo = DecisionTreeRegressor(criterion='mae')
#modelo.fit(X_treino, Y_treino)

#previsao_tree = modelo.predict(X_teste)
#previsao_tree

In [ ]:
#mean_squared_error(Y_teste, previsao_tree)

In [8]:
from sklearn.tree import DecisionTreeRegressor

modelo = DecisionTreeRegressor()
modelo.fit(X_treino, Y_treino)

previsao_tree = modelo.predict(X_teste)
previsao_tree

array([496.1, 583.6, 628.1, ..., 479. , 540.6, 504.3])

In [9]:
mean_squared_error(Y_teste, previsao_tree)

4224.737678

In [10]:
from sklearn.svm import SVR

modelo = SVR()
modelo.fit(X_treino, Y_treino)

SVR(C=1.0, cache_size=200, coef0=0.0, degree=3, epsilon=0.1, gamma='scale',
    kernel='rbf', max_iter=-1, shrinking=True, tol=0.001, verbose=False)

In [11]:
previsao_SVR = modelo.predict(X_teste)
previsao_SVR

array([536.2648346 , 459.80081621, 634.49325503, ..., 526.57234029,
       557.78780391, 485.94212609])

In [12]:
mean_squared_error(Y_teste, previsao_SVR)

2110.1659855384887

In [ ]:
from sklearn.kernel_ridge import KernelRidge

modelo_krr = KernelRidge(alpha=1.0)
modelo_krr.fit(X_treino[0:30000], Y_treino[0:30000])

In [ ]:
from sklearn.metrics import mean_squared_error

previsao_krr = modelo_krr.predict(X_teste)
mean_squared_error(Y_teste, previsao_krr)